### PR TITLE
Top right button vision

### PR DESCRIPTION
**Pull request by d4708**
this logic of the top right button is bit simpler for me. also includes latest branding updates.

### CODE REVIEW

**Comment by d4708** [comment]
I think, previous solution with left arrow not implements the _magic_ behavior of button, because it also includes drop down action that opening journal bar (discovery of today)

and new branding looks better for me.

**Comment by caryoscelus** [comment]
it does look better with branding ;) however since you started improving it , maybe it would also make sense to make a small popup hint like saying "click or drag me!" ?

**Comment by d4708** [comment]
I wish to make user experimenting, like me :D 

Let's it be without words the moving button is a key

**Comment by caryoscelus** [comment]
what's the target audience you want to see experimenting ?

i asked people around , they ask "WUT?" and only click~~

if you don't like words , perhaps arrows appearing on the button itself would be an understandable hint (unfortunately the cursor thing can be too small to notice)

also this completely ignores mobile situation where a person would never discover something is draggable :/

so in the future it should either be rid of and replaced with something else or there should be a tutorial on the first launch ...

**Comment by d4708** [comment]
I didn't understand this button too, but after console researching I adore it as is. That is a feature for me. Maybe some people wish to have something else - they are free to contribute.

If you wish, I can add, but I like it as is (with new logo where riza is something I can touch using ubuntu cursor version)

**Comment by caryoscelus** [comment]
probably just documenting it properly (there's no proper documentation yet , there wasn't any quite good) would suffice . anyway , your version is looking cooler so until someone else have time to enhance this further , i'll merge it

**Comment by d4708** [comment]
Doubts now with cursor. Because clicking button mostly, not dragging.

Tried to make cursor on mouse click using `:active` event, but it not works without JS.
Also tried to add arrows, titles in my local interface. Really something strange because maybe most valuable part in the UI.

**Pull request merged**
