### PR TITLE
Refactor shell scripts

### PR DESCRIPTION
**Pull request by TanvirOnGH**

### CODE REVIEW

**Comment by caryoscelus** [comment]
hi there , thanks for your interest !

didn't test it yet , but it seems there could be an issue when the repo already exists :

- `if [[ -d "$REPO_DIR" ]]; then cd "$REPO_DIR"`
- `cd "$REPO_DIR" && ./"$VENV_SCRIPT"`

**Comment by TanvirOnGH** [comment]
Works fine.

**Comment by caryoscelus** [comment]
i've tried testing it , but no luck getting `termux.sh` to work so far (could be unrelated to your changes though) . i'll look more into it in the coming days

**Comment by caryoscelus** [comment]
ah yeah , all works

**Pull request merged**
