### PR TITLE
Fix Annoying Migration functionality that doesn't work at all.

### PR DESCRIPTION
**Pull request by Zevobla**

### CODE REVIEW

**Comment by Zevobla** [comment]
Not good fix of #279 issue, but it works

**Comment by caryoscelus** [comment]
the logic seems a bit off (as it is in the current code as well, probably). i think if you're not interested in implementing migration the best next thing would be to simply warn if data is present in old locations and ignore

**Comment by Zevobla** [comment]
Zeronet Conservacy not creating configuration directory in macos at all and I want to make migration mechanism

**Comment by caryoscelus** [comment]
> not creating configuration directory in macos at all

huh, that's weird. can you debug what happens around https://github.com/zeronet-conservancy/zeronet-conservancy/blob/main/src/Config.py#L142. i don't have access to a mac right now

**Comment by Zevobla** [comment]
Can u pease say how can i debug function that you mentioned in config file?

**Comment by caryoscelus** [comment]
@Zevobla the easiest way is to add debug print statements. e.g.
```python
    def createPaths(self):
        self.start_dir.mkdir(parents=True, exist_ok=True)
        print(f'{self.start_dir.exists()=} {self.start_dir.is_dir()}')
        <...>
```

**Comment by Zevobla** [comment]
Uh, just print? I think in my case it doesn't run this function:
You have old data in `.`. Migrate to new format to `/Users/username/Library/Application Support/zeronet-conservancy`? [Y/n]n
Traceback (most recent call last):
  File "/Users/username/Documents/clear-zeronet/zeronet.py", line 4, in <module>
    from src.Config import config
  File "/Users/username/Documents/clear-zeronet/src/Config.py", line 860, in <module>
    config = Config(sys.argv)
             ^^^^^^^^^^^^^^^^
  File "/Users/username/Documents/clear-zeronet/src/Config.py", line 64, in __init__
    self.configurePaths(argv)
  File "/Users/username/Documents/clear-zeronet/src/Config.py", line 126, in configurePaths
    raise ex
  File "/Users/username/Documents/clear-zeronet/src/Config.py", line 124, in configurePaths
    self.start_dir = self.maybeMigrate(old_dir, new_dir, no_migrate, silent_migrate)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Documents/clear-zeronet/src/Config.py", line 194, in maybeMigrate
    return self.askMigrate(old_dir, new_dir, silent_migrate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Documents/clear-zeronet/src/Config.py", line 164, in askMigrate
    raise StartupError('Migration refused')
src.Config.StartupError: Migration refused

**Comment by caryoscelus** [comment]
@Zevobla please run with `--no-migrate` option, then we can see whether it creates directory or not

**Comment by Zevobla** [comment]
It works! It creating dir with flag --no-migrate!

**Pull request closed without merging**
